apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab0-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      nodeName: xyz
      containers:
      - name: pause
        image: k8s.gcr.io/pause