{{- if .Values.applications.prometheus.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-{{ .Values.orgId }}-staging
spec:
  destination:
    namespace: {{ .Values.orgId }}
    server: 'https://kubernetes.default.svc'
  sources:  
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: {{ .Values.applications.prometheus.chartsTargetRevision }}
      helm:
      {{- with .Values.promethues }}
        values: |-
          {{- toYaml . | nindent 12 }}
      {{- end}}
        valueFiles:
         - $values/values/prometheus-values.yaml
    - repoURL: 'https://github.com/fbalicchia/example-repo.git'
      targetRevision: charts-ns
      ref: values
  project: default
{{- end }}
