apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-{{ .Values.orgId }}-staging
spec:
  destination:
    name: ''
    namespace: {{ .Values.orgId }}
    server: 'https://kubernetes.default.svc'
  sources:  
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
        - $values/values/prometheus-values.yaml
      {{- with .Values.promethues }}
        values: 
          {{- toYaml . | nindent 10 }}
      {{- end}}
    - repoURL: 'https://github.com/fbalicchia/example-repo.git'
      targetRevision: final-struct
      ref: values
  project: default