{{- if .Values.applications.superset.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  name: superset-{{ .Values.orgId }}-staging
spec:
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   retry:
  #     limit: 5
  #     backoff:
  #       duration: 5s
  #       maxDuration: 3m0s
  #       factor: 2
  destination:
    namespace: {{ .Values.orgId }}
    server: 'https://kubernetes.default.svc'
  sources:  
    - repoURL: http://apache.github.io/superset
      chart: superset
      targetRevision: {{ .Values.applications.superset.chartsTargetRevision }}
  project: default
{{- end }}
