apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      exclude: '**/manifests/*'
      jsonnet: {}
      recurse: true
    path: orgs
    repoURL: https://github.com/fbalicchia/example-repo.git
    targetRevision: final-struct