apiVersion: v1
kind: Pod
metadata:
  name: lab3-1
spec:
  priorityClassName: p1
  containers:
  - name: pause
    image: k8s.gcr.io/pause
    resources:
      requests:
        ibm.com/gpu: 1
      limits:
        ibm.com/gpu: 1