apiVersion: v1
kind: Pod
metadata:
  name: lab3-3
spec:
  priorityClassName: p3
  containers:
  - name: pause
    image: k8s.gcr.io/pause
    resources:
      requests:
        ibm.com/gpu: 2
      limits:
        ibm.com/gpu: 2