apiVersion: v1
kind: Pod
metadata:
  name: lab3-4
spec:
  priorityClassName: p4
  containers:
  - name: pause
    image: k8s.gcr.io/pause
    resources:
      requests:
        ibm.com/gpu: 3
      limits:
        ibm.com/gpu: 3