apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo1
  template:
    metadata:
      labels:
        app: mongo1
    spec:
      containers:
      - name: mongo
        image: mongo:4
        imagePullPolicy: IfNotPresent