apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause2
  template:
    metadata:
      labels:
        app: pause2
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        resources:
          requests:
            cpu: 2
          limits:
            cpu: 2