apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause4
  template:
    metadata:
      labels:
        app: pause4
    spec:
      priorityClassName: p4
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        resources:
          requests:
            # ibm.com/gpu: 3
            cpu: 4
          limits:
            # ibm.com/gpu: 3
            cpu: 4