apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab1-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause3
  template:
    metadata:
      labels:
        app: pause3
    spec:
      priorityClassName: p3
      containers:
      - name: pause
        image: k8s.gcr.io/pause
        resources:
          requests:
            cpu: 4
          limits:
            # ibm.com/gpu: 2
            cpu: 4