apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-148-paas-staging-entrypoint
  namespace: argocd
spec:
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   retry:
  #     limit: 5
  #     backoff:
  #       duration: 5s
  #       maxDuration: 3m0s
  #       factor: 2
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: org-distribution
    repoURL: 'https://github.com/fbalicchia/example-repo.git'
    targetRevision: charts-ns-feature-branch-test
    helm:
      valueFiles:
         - $values/orgs/org-148/values.yaml
  - repoURL: 'https://github.com/fbalicchia/example-repo.git'
    targetRevision: charts-ns-feature-branch-test
    ref: values