#Values imported by a sinble orgs
orgId: org-148
jupyterhub:
  cull:
    enabled: false 
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    storage:
      capacity: 1Gi
promethues:
  server:
    replicaCount: 1
trino:
  server:
    workers: 1
  query:
    maxMemory: "1GB"

  coordinator:
    jvm:
      maxHeapSize: "2G"
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"

    config:
      memory:
        heapHeadroomPerNode: ""
      query:
        maxMemoryPerNode: "1GB"
  worker:
    jvm:
      maxHeapSize: "2G"
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"