apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-applications
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: apps
      repoURL: 'https://github.com/fbalicchia/example-repo.git'
      helm:
        valueFiles:
          - "./values-1000.yaml"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
