apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: org-147-paas-local
  namespace: argocd
spec:
  destination:
    namespace: orgocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      skipCrds: true
      values: |-
        orgId: org-147
    path: org-distribution
    repoURL: https://github.com/fbalicchia/example-repo.git
    targetRevision: final-struct
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
