orgId: org-147
jupyterhub:
  cull:
    enabled: false 
  prePuller:
    hook:
      enabled: false
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    storage:
      capacity: 1Gi





  

