# Organization configuration that follow helm templating rules for argoproj.io/v1alpha1 Application Spec
# this means that here we can applied all techniques used in helm 

orgId: org-147
jupyterhub:
  # start custom parameters
  # if true enabled the installation of jupyterhub application installation
  enabledApplication : true
  chartRevision: 2.0.0

  ## end custom parameters
  cull:
    enabled: false 
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    storage:
      capacity: 1Gi
promethues:
  server:
    replicaCount: 2
trino:
  server:
    workers: 1
  query:
    maxMemory: "1GB"

  coordinator:
    jvm:
      maxHeapSize: "2G"
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"

    config:
      memory:
        heapHeadroomPerNode: ""
      query:
        maxMemoryPerNode: "1GB"
  worker:
    jvm:
      maxHeapSize: "2G"
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"