orgId: org-147

##
# Version need to be put in this section and not in the values charts
##
applications:
  jupyterhub:
    enabled: false
    chartsTargetRevision: 2.0.0


jupyterhub:
  cull:
    enabled: false 
  prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
  scheduling:
    userScheduler:
      enabled: false
  singleuser:
    storage:
      capacity: 1Gi
promethues:
  server:
    replicaCount: 2
trino:
  server:
    workers: 1
  query:
    maxMemory: "1GB"

  coordinator:
    jvm:
      maxHeapSize: "2G"
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"

    config:
      memory:
        heapHeadroomPerNode: ""
      query:
        maxMemoryPerNode: "1GB"
  worker:
    jvm:
      maxHeapSize: "2G"
      gcMethod:
        type: "UseG1GC"
        g1:
          heapRegionSize: "32M"